/** Editorial examples, never evidence of work performed or measured results. */
export const demoStudies: Record<string, { challenge: string; flow: string[]; decision: string; reflection: string }> = {
  saia: { challenge: "Explorar cómo organizar el control de usuarios de una institución sin perder claridad entre perfiles y acciones.", flow: ["Acceso", "Buscar usuario", "Consultar perfil", "Editar información", "Confirmar"], decision: "Separar consulta y edición, mostrar permisos cerca de cada acción y confirmar los cambios importantes.", reflection: "Un sistema institucional necesita una jerarquía consistente antes de añadir más funciones." },
  kbichitos: { challenge: "Conectar clientes, productos, cotizaciones y pedidos dentro de un sistema administrativo comprensible.", flow: ["Dashboard", "Cliente", "Cotización", "Productos", "Pedido"], decision: "Agrupar módulos por tarea y conservar el contexto del cliente durante la creación de una cotización.", reflection: "La complejidad puede distribuirse en tareas pequeñas sin ocultar información necesaria." },
  "deportes-uvp": { challenge: "Facilitar la exploración de equipos, horarios y pruebas de ingreso para estudiantes.", flow: ["Deportes", "Equipo", "Horarios", "Prueba de ingreso"], decision: "Priorizar la información de acceso al equipo y permitir consultar horarios desde móvil.", reflection: "El contenido cambia durante una temporada; la estructura debe tolerar esa actualización." },
  "45-aniversario-uvp": { challenge: "Articular historia institucional, cuenta regresiva y una memoria destinada al aniversario número cincuenta.", flow: ["Aniversario", "Historia", "Memoria digital", "Próxima apertura"], decision: "Diferenciar la información disponible de la memoria que se abrirá en el futuro.", reflection: "Una experiencia temporal también necesita estados claros cuando el evento termina." },
  "auto-ayudate": { challenge: "Conectar una landing, un cotizador y una solicitud en un recorrido fácil de seguir.", flow: ["Información", "Cotizar", "Revisar", "Solicitar"], decision: "Mostrar el avance, explicar los campos y permitir corregir datos antes de enviar.", reflection: "Diseñar para una acción concreta implica trabajar también en errores, revisión y confirmación." },
  "encuentro-uvp": { challenge: "Ordenar programas académicos, clases muestra, diagnóstico y orientación sobre becas y costos.", flow: ["Explorar oferta", "Elegir programa", "Clases muestra", "Orientación"], decision: "Separar exploración académica de información práctica y conectar ambas con navegación contextual.", reflection: "Una oferta amplia se entiende mejor con agrupaciones claras y próximos pasos visibles." },
};
